export const SETRADARRINGSETS = "SETRADARRINGSETS";
export const SETSELECTEDRADARRINGSET = "SETSELECTEDRADARRINGSET";
export const SETRADARCATEGORYSETS = "SETRADARCATEGORYSETS";
export const SETSELECTEDRADARCATEGORYSET = "SETRADARCATEGORIES";
