
export const SETRADARCOLLECTION = "SETRADARCOLLECTION";
export const SETSOURCERADARINSTANCE = "SETSOURCERADARINSTANCE";
export const SETCURRENTRADARINSTANCE = "SETCURRENTRADARINSTANCE";
export const GETSOURCERADARINSTANCE = "GETSOURCERADARINSTANCE";