export const SETASSOCIATEDRADARTYPES = "SETASSOCIATEDRADARTYPES";
export const SETSHAREDRADARTYPECOLLECTION = "SETSHAREDRADARTYPECOLLECTION";
export const SETSELECTEDRADARTYPE = "SETSELECTEDRADARTYPE";
export const SETCURRENTUSER = "SETCURRENTUSER";
export const SETSHOWHISTORY = "SETSHOWHISTORY";
export const SETSHOWEDIT = "SETSHOWEDIT";
export const SETRADARTYPEHISTORY = "SETRADSARTYPEHISTORY";