export const SETASSOCIATEDRADARTYPES = "SETASSOCIATEDRADARTYPES"
export const SETRADARTYPECOLLECTION = "SETRADARTYPECOLLECTION";
export const SETSHAREDRADARTYPECOLLECTION = "SETSHAREDRADARTYPECOLLECTION"
export const SETSELECTEDRADARTYPE = "SETSELECTEDRADARTYPE"