export const SETASSOCIATEDRADARTYPES = "SETASSOCIATEDRADARTYPES";
export const SETRADARTYPECOLLECTION = "SETRADARTYPECOLLECTION";
export const SETSHAREDRADARTYPECOLLECTION = "SETSHAREDRADARTYPECOLLECTION";
export const SETSELECTEDRADARTYPE = "SETSELECTEDRADARTYPE";
export const SETSHOWHISTORY = "SETSHOWHISTORY";
export const SETSHOWEDIT = "SETSHOWEDIT";
export const SETRADARTYPEHISTORY = "SETRADSARTYPEHISTORY";
export const ADDTARGETUSERTOSTATE = "ADDTARGETUSERTOSTATE";